name = "Pôr Sentido"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/andrelug/igluhugo/blob/master/LICENSE.md"
description = "Um blog sobre um estilo de vida vegano, minimalista e com o amor em seu centro."
homepage = "https://www.igluonline.com"
tags = ["vegano", "vegan", "minimalismo", "amor", "blog", "pôr sentido"]
features = ["", ""]
min_version = 0.16

[author]
  name = "Amanda Mattar"
  homepage = "//github.com/andrelug"
